### ISSUE TITLE
Our LDbase custom block footer is missing again in production

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#149] opened 2021-07-09 15:08 UTC
It's the text that says this:  About LDbase
Welcome to LDbase, an NIH-funded collaboration between researchers and librarians to build a first-of-its-kind behavioral project-oriented data repository containing decades of knowledge from educational and developmental sciences on individuals across the full range of abilities. You can read more in our About section.
You may cite LDbase: Hart, S.A., Schatschneider, C., Reynolds, T.R., Calvo, F.E., Brown, B.J., Arsenault, B., Hall, M.R.K., van Dijk, W., Edwards, A.A., Shero, J.A., Smart, R. & Phillips, J.S. (2020). LDbase. http://doi.org/10.33009/ldbase.

**Comment by barsenault-fsu** [comment] 2021-07-15 18:03
I have re-placed the custom block in the Featured Bottom region.  I'm not sure why that happened.  There may have been an issue with the configuration import that caused this issue and the 404 errors on the data visualization of contributions.  Still investigating the cause.

**Comment by barsenault-fsu** [comment] 2021-07-22 19:16
This happened again when we updated production and we replaced it right away.  Still investigating.

**Comment by barsenault-fsu** [comment] 2021-07-22 20:41
I think the problem is the way Drupal stores information about custom blocks.  The content is stored in the database like other content, but the placement is stored as configuration which can be exported.  We can't create the custom block on Test, export it, and import it on Production, because the configuration would point to some wrong content id that doesn't exist on production and then throw an error.  I think because the configuration for the custom block doesn't exist in the import, it will keep removing its placement whenever we update production.  (The custom block content remains on production because it's content stored in the database but its placement gets lost.)

So I see 2 possibilities:
1) remember to replace the About LDbase block whenever Production is updated, or
2) change the About LDbase block back into the module-provided content that it was originally.  It means you would need a developer to edit the content, but do you expect to have to edit it often?

**Comment by barsenault-fsu** [comment] 2021-08-02 15:52
I discussed this with Tara after the last meeting, and to prevent the block from always disappearing when we update the site I made the block part of the content module again, which means it can only be edited by a developer.  It doesn't seem like text that should change often, so that seemed safe.

We updated production, and the block did not disappear, so I'm closing this issue.

**Closed as completed by barsenault-fsu** 2021-08-02 15:52 UTC
Labels: Domain: Display
