### ISSUE TITLE
404 messages

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#150] opened 2021-07-09 15:37 UTC
https://ldbase.org/browse-data   --->   LDbase contributions  --->  When you click on some of the dots, you get a 404 error. 
1. Maybe it's showing people we have deleted? 
2. Isn't this an outdated 404 message? I feel like around a year ago we decided on other text that should be there. Can you use that text?  If you can't find it, maybe something like: This page was not found. Feel free to contact us at ldbase@fcrr.org to let us know. It would be helpful to include the url link of the page you are on. Thanks for your feedback!

**Comment by trreynolds** [comment] 2021-07-09 15:40
Or maybe better to link them to our Report a Problem form? (but still ask them to copy the url of the page they are on before going there, so they can paste it into the form)

**Comment by barsenault-fsu** [comment] 2021-07-15 18:38
It appears to have been an issue with the configuration not properly updating.  The links work on Test.  Part of the view configuration does not seem to have gotten imported on Production.  We're investigating the cause.

I don't recall an updated text for the Access Denied (403) or Not Found (404) pages.  I based new text on what you wrote above in the issue.  They are at https://ldbase.org/access-denied and https://ldbase.org/not-found  The user gets routed to those pages when needed so they can't copy the URL of the page they are on (/access-denied or /not-found).  I ask them to copy the URL of the resources they were trying to access or reach.

**Comment by trreynolds** [comment] 2021-07-16 18:39
The new text is perfect and now I'll just edit the text as we go if I need to (using the Edit button on the screen you provided - thanks!). I'll remove the "needs review" label from this but leave the github open while we figure out the first part.

**Comment by barsenault-fsu** [comment] 2021-07-22 19:04
I'm not sure why the views configuration for the data visualizations hadn't updated correctly that time. Production has been updated again and the configuration updated fine.  Closing this issue.

**Closed as completed by barsenault-fsu** 2021-07-22 19:04 UTC
